'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin
    
    '''<summary>
    '''oBtnComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnComponent As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''oBtnPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnPart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''oBtnType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnType As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''oBtnModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnModule As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''oBtnUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnUsers As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''oBtnModuleCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oBtnModuleCapture As Global.System.Web.UI.WebControls.Button
End Class
